# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ba-kunder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9d11951a96f34382a12fda8c2722c5cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_29f86226d0c942ebbf64856ffb2333bc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9d11951a96f34382a12fda8c2722c5cc }}/ba-kunder:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ba-kunder'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9c418ac9ed348628b521002d2a2e3a5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9d11951a96f34382a12fda8c2722c5cc }}/ba-kunder:${{ github.sha }}'